//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassportManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PassportApplication
    {
        [RegularExpression("^FPS-[3|6][0][0-9]{4}$", ErrorMessage = "Passport Number is not valid")]
        [Required]
        public string PassportNumber { get; set; }
        [RegularExpression("^PASS-[0-9]{4}$", ErrorMessage = "UserID must be like PASS-1234")]
        [Required]
        public string UserID { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string City { get; set; }
        [RegularExpression("^[0-9]{6}$", ErrorMessage = "Zip must contain only 6 numbers.")]
        [Required]
        public string Zip { get; set; }
        [Required]
        public string TypeOfService { get; set; }
        [Required]
        public string BookletType { get; set; }
        [CustomDOI]
        [Required]
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Amount { get; set; }
        [Required]
        public string ReasonForReIssue { get; set; }
        [Required]
        public byte[] ProofOfCitizenship { get; set; }
        [Required]
        public byte[] Photo { get; set; }
        [Required]
        public byte[] BirthCertificate { get; set; }
        [Required]
        public string Status { get; set; }
        public string Comments { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
